manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('auth/', include('accounts.urls')),
]

task/urls.py
from django.urls import path
from .views import index, task_list, task_display, delete_list, complete_task, restart_task

app_name = 'task'
urlpatterns = [
	path('', index, name='index'),
	path('lists/', task_list, name='task_list'),
	path('lists/<int:pk>/', task_display, name='task_display'),
	path('lists/<int:pk>/delete/', delete_list, name='delete_list'),
	path('lists/<int:list_id>/task/<int:pk>/done/', complete_task, name='complete_task'),
	path('lists/<int:list_id>/task/<int:pk>/undo/', restart_task, name='restart_task'),
]

task/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class TaskList(models.Model):
	title = models.CharField(max_length=20)
	created = models.DateTimeField(auto_now=True)
	creator = models.ForeignKey(User, null=True, related_name='tasklists', on_delete=models.CASCADE)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return self.title

	def count(self):
		"""Returns count of all tasks in related list"""
		return self.tasks.count()

	def count_complete(self):
		"""Returns count of all complete tasks in related list"""
		return self.tasks.filter(is_complete=True).count()

	def count_incomplete(self):
		"""Returns count of all incomplete tasks in related list"""
		return self.tasks.filter(is_complete=False).count()

class Task(models.Model):
	creator = models.ForeignKey(User, null=True, related_name='tasks', on_delete=models.CASCADE)
	tasklist = models.ForeignKey(TaskList, related_name='tasks', on_delete=models.CASCADE)
	description = models.CharField(max_length=255)
	created = models.DateTimeField(auto_now=True)
	completed_at = models.DateTimeField(null=True)
	is_complete = models.BooleanField(default=False)

	class Meta:
		ordering = ('tasklist', 'created', 'completed_at')

	def __str__(self):
		return self.description
	
	def complete(self):
		self.is_complete = True
		self.completed_at = timezone.now()
		self.save()

	def restart(self):
		self.is_complete = False
		self.completed_at = None
		self.save()

task/forms.py
from django import forms

def widget_attrs(placeholder):
	return {'class': 'form-control mb-2 mr-md-2', 'placeholder':placeholder}

def form_kwargs(widget, label, max_length):
	return {'widget':widget, 'label': label, 'max_length': max_length}

class TaskListForm(forms.Form):
	title = forms.CharField(
		**form_kwargs(
			widget = forms.TextInput(attrs=widget_attrs('Start a new list of tasks')),
			label='',
			max_length=20
			)
		)

class TaskForm(forms.Form):
	description = forms.CharField(
		**form_kwargs(
			widget = forms.TextInput(attrs=widget_attrs('Describe your tasks here')),
			label='',
			max_length=255
			)
		)

task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from task.forms import TaskListForm, TaskForm
from task.models import TaskList, Task

from django.utils import timezone

def index(request):
	"""Displays the Landing page"""
	context = {'form':TaskListForm()}
	return render(request, 'task/index.html', context)

@login_required(login_url='/auth/login/')
def task_list(request):
	"""Handles form from the landing(index) page and sends a list of task lists for display on 'lists' page"""
	if request.method == 'POST':
		form = TaskListForm(request.POST)
		user = request.user if request.user.is_authenticated else None
		if form.is_valid():
			tasklist = TaskList(
				title=request.POST['title'],
				created=timezone.now(),
				creator=user,
				)
			tasklist.save()
			return redirect('task:task_list')
	user = request.user if request.user.is_authenticated else None
	tasklists = TaskList.objects.filter(creator=user).reverse() #Latest comes first
	length = len(tasklists)
	context = {
		'form':TaskListForm(),
		'len':length,
		'tasklists':tasklists
		}
	return render(request, 'task/lists.html', context)

def task_display(request, pk):
	if request.method == 'POST':
		form = TaskForm(request.POST)
		user = request.user if request.user.is_authenticated else None
		if form.is_valid():
			task = Task(
				tasklist_id = pk,
				description=request.POST['description'],
				created=timezone.now(),
				creator=user,
				)
			task.save()
			return redirect('task:task_display', pk)

	task_list = get_object_or_404(TaskList, pk=pk)
	user = request.user if request.user.is_authenticated else None
	tasks = task_list.tasks.filter(creator=user)
	length = task_list.count()
	complete_length = task_list.count_complete()
	incomplete_length = task_list.count_incomplete()
	if length != 0:
		progress = round((complete_length/length)*100, 0)
	else:
		progress = 0
	context = {
		'task_list':task_list,
		'tasks':tasks,
		'len':length,
		'complete':complete_length,
		'incomplete':incomplete_length,
		'progress':progress,
		'form':TaskForm(),
		}
	return render(request, 'task/tasks.html', context)

def delete_list(request, pk):
	tasklist = TaskList(id = pk)
	tasklist.delete()
	return redirect('task:task_list')

def complete_task(request, pk, list_id):
	task = Task(id = pk, tasklist_id=list_id)
	task.description = Task.objects.get(pk=pk).description
	task.is_complete = True
	task.completed_at = timezone.now()
	task.save()
	return redirect('task:task_display', list_id)

def restart_task(request, pk, list_id):
	task = Task(id = pk, tasklist_id=list_id)
	task.description = Task.objects.get(pk=pk).description
	task.is_complete = False
	task.completed_at = None
	task.save()
	return redirect('task:task_display', list_id)

task/templates/task/index.html
{% extends 'base.html' %}

{% block newlist %}
<div class="row h-75 justify-content-center align-items-center  text-center">
    <form class="form-group text-center" action="{% url 'task:task_list' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline mb-2 ">Submit</button>
    </form>
</div>
{% endblock newlist %}

task/templates/task/lists.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Tasklists - Timothy {% endblock title %}

{% block lists %}
<div class="h-75 justify-content-center align-items-center  text-center">
    <form class="form-group text-center" action="{% url 'task:task_list' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline mb-4 ">Submit</button>
    </form>
    {% if len == 0 %}
    <div class="text-center mt-4">
        <h2> It looks like your schedule is clear... </h2>
    </div>
    {% else %}
    <h4> <b> Task Lists </b> <small class="text-muted">{{len}}</small></h4>
    <div class="text-left">
        <div class="list-group">
        <div class="list-group-item list-group-item-success">
            <div class="float-left"><h5><b>List Title</b></h5></div>
            <div class="float-right"><h5><b>Created</b></h5></div>
            </div>
            {% for list in tasklists %}
            <div class="list-group-item list-group-item-action">
                <a href="{{ list.id }}" class="custom-link"> <b>{{ list.title }}</b> </a>
                <div class="float-right"> {{ list.created|naturaltime }} </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock lists %}

task/templates/task/tasks.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Tasks - {{ task_list.title }} {% endblock title %}

{% block lists %}
<div class="h-75 justify-content-center align-items-center  text-center">
    <h4><b>{{ task_list.title | title }}</b></h4> <small class="text-muted">Created {{ task_list.created|naturaltime }}
    </small>
    <form class="form-group" action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline mb-2 ">Submit</button>
    </form>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:{{progress}}%" aria-valuenow="{{progress}}" aria-valuemin="0"
            aria-valuemax="100">{{progress}}%</div>
    </div>
    {% if len == 0 %}
    <div class="text-center mt-4">
        <h2> It looks like this list has not tasks yet... </h2>
    </div>
    {% else %}
    <div class="row text-left">
        <div class="col-sm-6">
            <h4><b> {{ incomplete }} Pending</b></h4>
            {% for task in tasks %}
            {% if not task.is_complete %}
            <li class="list-group-item">
                {{ task.description }}
                <a href="task/{{task.id}}/done/">
                    <button class="btn btn-outline-warning btn-sm float-right"> &#10005; </button>
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </div>
        <div class="col-sm-6">
            <h4><b> {{ complete }} Completed</b></h4>
            {% for task in tasks %}
            {% if task.is_complete %}
            <li class="list-group-item">
                {{ task.description }}
                <a href="task/{{task.id}}/undo/">
                    <button class="btn btn-outline-success btn-sm float-right"> &check; </button>
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    <div class="container text-right pt-4">
        <hr>
        <a href="{% url 'task:delete_list' task_list.id %}">
            <button type="" class="btn btn-outline-danger mb-2 ">Delete</button>
        </a>
    </div>
</div>
{% endblock lists %}