accounts/urls.py
from django.urls import path
from accounts.views import register, login_view, logout_view, profile

app_name = 'accounts'
urlpatterns = [
	path('register/', register, name='register'),
	path('login/', login_view, name='login'),
	path('logout/', logout_view, name='logout'),
	path('profile/', profile, name='profile')
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('auth/', include('accounts.urls')),
]

task/urls.py
from django.urls import path
from .views import index, task_list, task_display, delete_list, complete_task, restart_task

app_name = 'task'
urlpatterns = [
	path('', index, name='index'),
	path('lists/', task_list, name='task_list'),
	path('lists/<int:pk>/', task_display, name='task_display'),
	path('lists/<int:pk>/delete/', delete_list, name='delete_list'),
	path('lists/<int:list_id>/task/<int:pk>/done/', complete_task, name='complete_task'),
	path('lists/<int:list_id>/task/<int:pk>/undo/', restart_task, name='restart_task'),
]

templates/base.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Optional Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&display=swap" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}" />

    <title>{% block title %}{% endblock title %}</title>
</head>

<body class="bg-light">
    <div class="container h-100">
        <div class="d-flex flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h2 class="my-0 mr-md-auto nav-brand"><a href="{% url 'task:index' %}">Task Manager</a></h2>
            <nav class="my-2 my-md-0 mr-md-3">
                {% if not user.is_authenticated %}
                <a class="p-3" href="{% url 'accounts:login' %}">LOGIN</a>
                <a class="p-3" href="{% url 'accounts:register' %}">REGISTER</a>
                {% else %}
                <a class="p-3" href="#">API</a>
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                        {{ user.username|upper }}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'task:task_list' %}">My Tasks</a>
                        <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </div>
                {% endif %}
            </nav>
        </div>
        {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
</body>

</html>